### ISSUE TITLE
Unify openshift cronjob deployment approach.

### ISSUE THREAD

**Issue by sakalosj** [packit/deployment#112]
Current state:
* delete-pvcs and import-images use own make file
* validation is deployed via separate target in root make file

The separate target in the root make file is preferred.

Consider incorporating into the global deployment process (`make deploy`).

**Comment by jpopelka** [comment]
Another thing to improve:

@lbarcziova was having a problem that the [validation job](https://github.com/packit/deployment/blob/master/cron-jobs/validation/openshift/job-run-validation.yaml) was at some point not able to download [the image from Docker Hub](https://hub.docker.com/repository/docker/usercont/packit-service-validation).
The reason (correct me if I'm wrong) was that she'd built & pushed the image with podman.
So if the cluster has problems with podman built&pushed images, then we should enforce using docker in those makefile targets.

**Comment by TomasTomecek** [comment]
and/or report the podman problem is it gets resolved in future

**Comment by jpopelka** [comment]
> and/or report the podman problem is it gets resolved in future

yes, it might actually be the same problem as https://github.com/packit/packit-service/issues/680

**Comment by lachmanfrantisek** [comment]
@jpopelka Looks like you want this opened.

**Comment by jpopelka** [comment]
Whoever will do this, please also change [rebuild-base-image](https://github.com/packit/deployment/blob/master/cron-jobs/rebuild-base-image/rebuild-base-image.yaml) to run once a week and not every day.
So that my images are not rebuilding over and over again when I'm working on something for more days.

**Comment by jpopelka** [comment]
> and/or report the podman problem is it gets resolved in future

https://github.com/docker/hub-feedback/issues/1871 looks like the same problem

**Comment by TomasTomecek** [comment]
latest comment in the hub tracker seems to indicate the images can now be pulled

**Comment by jpopelka** [comment]
> validation is deployed via separate target in root make file

I don't see any such target in the [main Makefile](https://github.com/packit/deployment/blob/main/Makefile), only in [cron-jobs/validation/Makefile](https://github.com/packit/deployment/blob/main/cron-jobs/validation/Makefile).
So all the cron-jobs are being deployed by their own Makefiles. Closing

All the other comments are being resolved by building images via Github Actions and using Quay.io as image registry.
