### ISSUE TITLE
Trigger packit-service image build after a new change to ogr or packit master is merged

### ISSUE THREAD

**Issue by sakalosj** [packit/deployment#113]
Try to figure out how to trigger packit-service image rebuild when a new change is merged to ogr or packit master

Possible solutions currently in my mind:
* via DockerHub: add webhook 
  * seems inflexible - webhook is triggered when any of specified builds is finished
* via zuul-ci:
  * probably will require more complex changes

**Comment by TomasTomecek** [comment]
I'd love to groom this on our next grooming.
