### ISSUE TITLE
Failed to patch object: sts.packit-worker, updates to statefulset spec are forbidden

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#238]
From time to time `make deploy` fails with 

fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Failed to patch object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"StatefulSet.apps \\\\\"packit-worker\\\\\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than \\'replicas\\', \\'template\\', and \\'updateStrategy\\' are forbidden.\",\"reason\":\"Invalid\",\"details\":{\"name\":\"packit-worker\",\"group\":\"apps\",\"kind\":\"StatefulSet\",\"causes\":[{\"reason\":\"FieldValueForbidden\",\"message\":\"Forbidden: updates to statefulset spec for fields other than \\'replicas\\', \\'template\\', and \\'updateStrategy\\' are forbidden.\",\"field\":\"spec\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}

One has to `oc delete sts/packit-worker` and re-run again.

**Comment by mfocko** [comment]
related to repository cache? same as Friday's redeployment?

**Comment by jpopelka** [comment]
Thanks for the explanation.
So there's probably nothing we can do about it and since it happens only when we change something in the spec it doesn't make sense trying to create some workaround for it.
Closing.
