### ISSUE TITLE
Conditionaly (not) create packit-worker-repository-cache PVC

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#244]
The [packit-worker playbook](https://github.com/packit/deployment/blob/main/openshift/packit-worker.yml.j2#L59) requests 16Gi PVC for repository cache.
We use the playbook also to deploy [hardly](https://github.com/packit/hardly), which doesn't use that PVC (yet).
And since our quota is reaching a hard limit we need to figure out how to conditionaly not request that PVC when deploying hardly.

(Disclaimer: I manually removed that part from the playbook before deploying stg/prod.)

**Comment by lachmanfrantisek** [comment]
Making it optional would be nice also for the work @lbarcziova is currently working on -- we want to avoid creating repository volumes for short-running workers.
