### ISSUE TITLE
Fix the deployment tests

### ISSUE THREAD

**Issue by csomh** [packit/deployment#310]
Deploying on the cluster started failing, b/c images couldn't be pulled from the image streams. No clue why.

Until fixed 71f67c0 disabled the tests.

Figure out why the failure occurred, fix it, and re-enable the deployment test.

**Comment by lachmanfrantisek** [comment]
Sadly, we don't have capacity to work on this. Also, there is a chance we can use MP+ for that. (And we will know more when researching it.)

I am closing this issue, but please reopen if you think we should spend the time on this.

**Comment by jpopelka** [comment]
For the record, the exact problem was/is:
`! error: Import failed (InternalError): Internal error occurred: missing signature key`
when the (oc cluster up-ped) OpenShift tried to import the image(s)

**Comment by jpopelka** [comment]
Fixes in #455
