### ISSUE TITLE
Automate usage of `changelog.py`

### ISSUE THREAD

**Issue by FrNecas** [packit/deployment#320]
Our release process is already quite automatic but we can take it even one step further!

The changelog script could be automatically run based on some kind of indication that we want to create a release and a PR for the release could be created automatically so that we would just have to review and merge. Perhaps Github actions could be used for this?

We also need to keep in mind that the not always is the generated output perfect and may need some manual love so the approach must support this flow.

**Comment by FrNecas** [comment]
Still relevant

**Comment by lachmanfrantisek** [comment]
I hope it's already covered by the work we've done during the hackfests... @FrNecas, please, reopen the issue if I get that wrong.
