### ISSUE TITLE
Add redis & postgres image streams

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#327]
On one of the recent architecture meetings, we (cc @praiskup) realized that we don't update our redis & postgres, i.e. we still use the same versions of container images even though they've been meanwhile updated in the external container registry.

TODO:
- Add image streams for [redis](https://github.com/packit/deployment/blob/ac058d2e663e8e7d6886be1b9547a65796e02d68/openshift/redis.yml#L21) & [postgres](https://github.com/packit/deployment/blob/ac058d2e663e8e7d6886be1b9547a65796e02d68/openshift/postgres.yml.j2#L43), they will (as the already existing ones) have `scheduled: {{ auto_import_images }}` so for `stg` they'd be automatically synchronized with the external image registry and for `prod` they'd be synchronized manually/periodically by our import-images cron job. Use those image streams in the DeploymentConfigs.
- Add those image streams into [import-images cron job](https://github.com/packit/deployment/blob/main/cron-jobs/import-images/import-images.sh), re-build and redeploy it.
- Bonus point: since it means redeploying the redis & postres, we can, at the same time, change those from DeploymentConfig to Deployment, which is basically [a successor of DC](https://docs.openshift.com/container-platform/4.9/applications/deployments/what-deployments-are.html#deployments-kube-deployments_what-deployments-are) and  [in general preferred](https://docs.openshift.com/container-platform/4.9/applications/deployments/what-deployments-are.html#deployments-comparing-deploymentconfigs_what-deployments-are) in OCP 4.

**Comment by jpopelka** [comment]
OTOH, it's not critical since the `:latest` images are used when the pods are restarted upon a cluster update, which in our case (auto-prod) happens about once/twice a month. I've just checked and the postgres image used is 2 weeks old.
So the only benefit I see now is that we'd have several days to test the newer images on staging first before moving prod to them.

**Comment by csomh** [comment]
This happens as the cluster is upgraded.
