### ISSUE TITLE
Bitwarden CLI broken on Fedora Linux 36

### ISSUE THREAD

**Issue by csomh** [packit/deployment#329]
I noticed only today, that the `bw get item secrets-tls-certs` is not working on Fedora Linux 36. This makes `download_secrets.sh` unusable.

```
$ bw --version
1.22.1
```

The above seems to be happening, b/c `bw` fails to decrypt the `name` and `notes` fields of secrets shared within an organization (this does not happen to secrets of my own). When I get a secret by ID, I see lines like:

```json
...
  "name": "[error: cannot decrypt]",
  "notes": "[error: cannot decrypt]",
...
````

Indeed, I can run `bw get item '[error: cannot decrypt]'`, which will complain that there are more than one items with this name:

```
$ bw get item '[error: cannot decrypt]'
More than one result was found. Try getting a specific object by `id` instead. The following objects were found:
...
```

bitwarden/clients#2726 is just about this issue, and I made a note that it's also happening on Fedora Linux 36.

The issue might be that these newer distros switched to use openssl3, but I don't know enough about crypto to be able to figure out a solution for this. Theoretically openssl1.1 is still present in Fedora to serve as a compatibility layer, but for some reason it doesn't seem to work.

Until then the solution is to run deployments from a container environment which is running Fedora Linux 35.

**Comment by csomh** [comment]
I worked around this issue with `toolbox` after all:

1. Install toolbox: `dnf install toolbox`.
2. Create a new toolbox using Fedora Linux 35: `toolbox create --distro fedora --release 35`.
3. Enter the toolbox env: `toolbox enter fedora-toolbox-35`.
4. Install the dependencies needed to make a deployment: `dnf install ansible python3-openshift jq make`.
5. B/c I had `bw` and `oc` installed in `~/.local/bin`, those were already available in the toolbox container.
6. `oc login` and `bw login`
7. Make the deployments.

After starting to use the toolbox env I noticed that `bw unlock --check` kept reporting that the vault is locked all the time, even if it was just unlocked. I'm not sure if the two is related, though.

**Comment by jpopelka** [comment]
> I worked around this issue with `toolbox` after all:

Works nicely for me, thanks!

> I noticed that `bw unlock --check` kept reporting that the vault is locked all the time

I don't see the problem. I have this in my ~/.bashrc
```bash
alias bwunlock='bw unlock --check || export BW_SESSION="$(bw unlock --raw)"'
```
I run `bwunlock` only once and then the vault is unlocked for all scripts I run in that terminal session.

Also my bw version is 
```bash
$ bw -v
2022.6.2
```

**Comment by jpopelka** [comment]
[OPENSSL_CONF=/dev/null DEPLOYMENT=stg make download-secrets](https://github.com/bitwarden/clients/issues/2726#issuecomment-1292153245)
works around the problem for me (F36).

**Comment by jpopelka** [comment]
@csomh once you find a minute, can you try the [latest CLI](https://github.com/bitwarden/clients/releases/tag/cli-v2023.1.0) ?

It seems to work OK now (F37). I don't see any
```yaml
  "name": "[error: cannot decrypt]",
  "notes": "[error: cannot decrypt]",
```
in `bw list items` and for example `bw get item secrets-tls-certs` returns the item just fine.

**Comment by csomh** [comment]
Indeed! It seems it was fixed in the [latest release](https://github.com/bitwarden/clients/releases/tag/cli-v2023.1.0). Thanks for checking! I'll revert the disabling the system configs for OpenSSL.
