### ISSUE TITLE
CentOS Stream based sclorg postgres & redis images

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#335]
Currently, we're using [Centos 7 based postgres & redis images](https://quay.io/organization/centos7).

In https://quay.io/organization/sclorg there are CentOS Stream 8 and 9 based postgres and redis images:

- https://quay.io/repository/sclorg/postgresql-13-c8s (since sclorg/postgresql-container#437)
- https://quay.io/repository/sclorg/postgresql-13-c9s
- https://quay.io/repository/sclorg/redis-6-c8s
- https://quay.io/repository/sclorg/redis-6-c9s

Would be nice to do this together with #327 

EDIT: https://fedoramagazine.org/community-container-images-available-for-applications-development/
EDIT2: https://bugzilla.redhat.com/show_bug.cgi?id=1950420

**Comment by TomasTomecek** [comment]
looks like a great December/Christmas task :)
