### ISSUE TITLE
changelog generation: markdown is lost

### ISSUE THREAD

**Issue by TomasTomecek** [packit/deployment#346]
This is a bit frustrating that GitHub strips markdown formatting in the commit metadata in a merge commit.

We should instead parse description of a PR to get the changelog entry instead of the merge commit.

**Comment by lachmanfrantisek** [comment]
Note that this requires calls to GitHub API -- so, ideally, a token is required. The public calls are limited...

**Comment by FrNecas** [comment]
Done
