### ISSUE TITLE
[Spike-ish] Use kubernetes.core.k8s apply=true by default?

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#360]
The [apply parameter docs](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html#parameter-apply) says: 
"`apply` compares the desired resource definition with the previously supplied resource definition, ignoring properties that are automatically generated. `apply` works better with Services than `force=yes`."

I don't quite understand how it's actually different from the default behavior (what are the "properties that are automatically generated"?), but @csomh says it helps when there are properties being removed in the object.

Investigate:
- What it actually does?
- Why [some tasks already use it](https://github.com/packit/deployment/blob/4192911bebc8a26c365cf4f98a38f5526f3de8ef/playbooks/deploy.yml#L308) and others not?
- Would it make sense to [default](https://github.com/packit/deployment/blob/4192911bebc8a26c365cf4f98a38f5526f3de8ef/playbooks/deploy.yml#L52) to `apply=true`?

**Comment by mfocko** [comment]
### What it actually does?

In the simple terms, it makes sure that the definition that is to be deployed matches the one that is already deployed. The difference has already manifested few times, e.g., when @majamassarini was adjusting the `/dev/shm` for the postgres deployment (bedef2026c84ea00bb329799cc9bef81687fe88d), the change did not get deployed.

### Why [some tasks already use it](https://github.com/packit/deployment/blob/4192911bebc8a26c365cf4f98a38f5526f3de8ef/playbooks/deploy.yml#L308) and others not?

not sure

### Would it make sense to [default](https://github.com/packit/deployment/blob/4192911bebc8a26c365cf4f98a38f5526f3de8ef/playbooks/deploy.yml#L52) to apply=true?

Not really. I would definitely avoid it with the “critical” services (e.g., postgres), last time I tried deploying production with `apply=true` the redeployment of everything caused a small downtime.
