### ISSUE TITLE
SPIKE: Auto-scalling of workers

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/deployment#362]
Take a look at the possible ways how to scale our workers automatically, when needed and provide the findings as a document in [the research repo](https://github.com/packit/research).

TODO:
* [ ] describe the possible triggers for the scaling (and how to get such info)
* [ ] propose options we have for the implementation
* [ ] discuss the findings with the team and agree on a solution we will implement
* [ ] create follow-up cards (=issues) to implement it

**Comment by jpopelka** [comment]
- packit/research#153
- packit/packit-service#1584
- packit/deployment#???
