### ISSUE TITLE
Move staging projects from auto-stage to auto-prod

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#380]
Per Hubert's e-mail from 9/29/22, the auto-stage cluster will be de-provisioned after we move our staging projects to the auto-prod cluster.

1. Create `packit-stg`, `stream-stg` and `fedora-source-git-stg` projects at auto-prod cluster.
2. Switch the [DNS](https://domains.google.com/registrar/packit.dev/dns). We probably want to [regenerate the TLS certs](https://github.com/packit/deployment/blob/main/docs/tls-certs.md) but I'm not sure.

(For each project)

3. Update the `host` in [vars/*/stg[_template].yaml](https://github.com/packit/deployment/tree/main/vars)
4. First, deploy only postgres (`DEPLOYMENT=stg SERVICE=xyz make deploy TAGS=postgres`); [copy db data](https://github.com/packit/packit-service/blob/main/CONTRIBUTING.md#using-live-data-locally)
5. Deploy the rest of the project (`DEPLOYMENT=stg SERVICE=xyz make deploy`)
6. Add the team members to the project. (`Developer` -> `Project` -> `Project Access`)
7. Scale down the old project

**Comment by TomasTomecek** [comment]
This is how we worked in the OpenShift Online timeline, so nothing new to us.

I actually like that all our deployments will be on a single cluster: will make things more straightforward and potential cluster problems will be consistent.
