### ISSUE TITLE
Rename stream to [centos-]stream-source-git

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#381]
For the Fedora Source-git bot we have `fedora-source-git` Openshift project and DNS domain.
But the Openshift project and DNS domain for CentOS Stream Source-git bot has only "stream", i.e. `stream-[prod|stg]` projects in Openshift and `[prod|stg].stream.packit.dev` DNS domains.

Some time ago we discussed with @csomh that the CentOS Stream Source-git bot projects and DNS domain names should also include the "source-git".

- [ ]  Rename DNS domains: `*[.stg].stream.packit.dev` to `*[.stg].stream-source-git.packit.dev` 
  - [ ] [DNS records](https://domains.google.com/registrar/packit.dev/dns)
  - [ ] [Regenerate TLS certs](https://github.com/packit/deployment/blob/main/docs/tls-certs.md#obtaining-a-lets-encrypt-tls-cert-using-certbot)
  - [ ] Update URLs in [src group hooks settings](https://gitlab.com/groups/redhat/centos-stream/src/-/hooks) & [rpms group hooks settings](https://gitlab.com/groups/redhat/centos-stream/rpms/-/hooks) (Ask Tomas or Stephen Gallagher, they have access)
- [ ] Rename Openshift projects: `stream-[prod|stg]` to `stream-source-git-[prod|stg]`, update [deployment/vars](https://github.com/packit/deployment/tree/main/vars/stream)

Would be nice to do this together with #380

**Comment by lachmanfrantisek** [comment]
Sadly, we don't have capacity to work on this.

We can easily reopen if we need to.
