### ISSUE TITLE
Bump base image to F36/37

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#384]
[Fedora 35](https://github.com/packit/deployment/blob/main/containers/Dockerfile.base#L4) is getting EOL [mid-December](https://fedorapeople.org/groups/schedule/f-37/f-37-key-tasks.html).

~~We need to port playbooks to [ansible>=5](https://src.fedoraproject.org/rpms/ansible) but still keep compatibility with ansible-2 because of the [packit-service-tests-openshift](https://github.com/packit/packit-service/blob/main/.zuul.yaml#L21) which [runs the deployment](https://github.com/packit/packit-service/blob/main/files/deployment.yaml#L94) on a [centos-7 node](https://github.com/packit/packit-service-zuul/blob/main/zuul.d/jobs.yaml#L56) with ansible-2.~~

Any other blocker?

**Comment by csomh** [comment]
packit/packit-service#1681 was solved. So I think this is safe to do.

After this is done, remember to merge packit/dashboard#182. IIRC the dashboard would stop working otherwise.

**Comment by jpopelka** [comment]
I tried to install ansible-6 from PyPI in the (still F35-based) base image and all dependent images (packit, p-s worker/service, fedmsg) were rebuilt successfully so I think we're free to go.

The problem with ansible 2 and 5 compatible playbooks, which I initially described above is not related to this.
