### ISSUE TITLE
Run validation job on GitLab

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/deployment#401]
Improve [the validation script](https://github.com/packit/deployment/tree/main/cron-jobs/packit-service-validation) to run on the `GitLab` as well, namely, we can use the https://gitlab.com/packit-service/hello-world repo.

* [ ] Info about deployment should cover forge instance:
  * https://github.com/packit/deployment/blob/c3a9a739a859ba2e7ec8bf6f54f12a5a8200c8d6/cron-jobs/packit-service-validation/packit-service-validation.py#L43-L51
* [ ] Replace the Github-only code with OGR:
  *  e.g. https://github.com/packit/deployment/blob/c3a9a739a859ba2e7ec8bf6f54f12a5a8200c8d6/cron-jobs/packit-service-validation/packit-service-validation.py#L138-L146
* [ ] Make the whole code forge-independent:
  * e.g. https://github.com/packit/deployment/blob/c3a9a739a859ba2e7ec8bf6f54f12a5a8200c8d6/cron-jobs/packit-service-validation/packit-service-validation.py#L23

---
*Part of packit/packit-service#1821 epic.*

**Comment by lbarcziova** [comment]
The cron job with the new image and configuration was deployed, let's wait how it will go tomorrow, and then we can close this.
