### ISSUE TITLE
Refine alerting setup

### ISSUE THREAD

**Issue by TomasTomecek** [packit/deployment#402]
We're getting too many alerts from the alert manager and successfully ignoring most of them. Not cool.

Let's refine the existing setup and improve it:
* send less emails
* separately configure SLO-related alerts
* think about configuration for failing tasks
  * especially document how are these meant to be processed

**Comment by TomasTomecek** [comment]
@xsuchy thank you for bringing this up!

**Comment by lachmanfrantisek** [comment]
We refine the setup on the go each week. We don't need any special card for that.
