### ISSUE TITLE
Provide a clear list of tools, services and processes for investigation

### ISSUE THREAD

**Issue by TomasTomecek** [packit/deployment#404]
You're a Chief of Monitors. Something goes wrong. Panic 😨😱. "How do I find out what's wrong?"

TODO:
- [ ] Create a new document with a complete list of
  - [ ] tools
  - [ ] services
  - [ ] people
  - [ ] that can help you with an investigation of alerts and sentry events

It's fine to provide only links to other documents or documentation sites.

**Comment by mfocko** [comment]
This has popped up recently and been picked by Maja (hence assigning); we've already had a meeting yesterday to come up with some ideas for more comprehensive docs.

The docs for this are “somewhat” started in the deployment repository, I propose to turn the _Monitoring_ and _Logs_ there into a separate subcategory (will open a PR in the evening) and add more pages with the outcomes from yesterday.
