### ISSUE TITLE
CentOS Stream 9 based base image

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#410]
The base image, which we use for building

- [packit](https://github.com/packit/packit/blob/main/Containerfile#L3)
- [worker](https://github.com/packit/packit-service/blob/main/files/docker/Dockerfile.worker#L3)
- [service/API](https://github.com/packit/packit-service/blob/main/files/docker/Dockerfile#L3)
- [fedmsg](https://github.com/packit/packit-service-fedmsg/blob/main/Dockerfile#L1)
- [sandcastle](https://github.com/packit/sandcastle/blob/main/Dockerfile#L3)
- [dashboard](https://github.com/packit/dashboard/blob/main/Dockerfile#L1)

images, is [Fedora based](https://github.com/packit/deployment/blob/main/containers/Dockerfile.base#L4).

Tomáš has suggested using CentOS Stream 9 instead so that we don't have to bump the base image (to newer Fedora) so often.

I checked what base image Software Collections use (we use their c9s based [redis](https://github.com/sclorg/redis-container) & [postgres](https://github.com/sclorg/postgresql-container)) and if I check the [right place](https://github.com/sclorg/s2i-base-container/blob/master/core/Dockerfile.c9s#L2) it's [quay.io/centos/centos:stream9](https://quay.io/repository/centos/centos?tab=tags).

~~The aim of this spike is to check whether all the dependencies installed in our (above-mentioned) images are available for c9s as well and what's missing.~~

**Comment by TomasTomecek** [comment]
I hope that we could install most of them using PyPI & we could also lock down the deps to precise versions

**Comment by mfocko** [comment]
How reasonable would be building them in Copr just for our images?

---

Given my suggestion I expect the cost of maintaining them in Copr to be higher than bumping the image. :/

**Comment by mfocko** [comment]
On the other hand, I would not worry about the `sandcastle` image that much, we have a lot of build dependencies for our users included, once we move to Copr the list will shorten. I'd expect `wheel`, `setuptools` and maybe `gobject-…` to stay on the list.
