### ISSUE TITLE
Extend the daily validation tests

### ISSUE THREAD

**Issue by lbarcziova** [packit/deployment#429]
Think of the new use cases (discuss with the team, check the new features) that our daily validation script could validate and adjust [the script](https://github.com/packit/deployment/blob/main/cron-jobs/packit-service-validation/packit-service-validation.py) accordingly. Also adjust the existing use-cases and remove the PRs that are not needed anymore.

Suggestions:
- [ ] identifiers 
- [x] tests with skip_build option
- [ ] targets mapping for build-test
~~- [ ] downstream jobs~~
- [ ] vm-image builds
- [x] recreate all validation PRs to get rid of `srpm_build_deps-not-defined` checks

**Comment by TomasTomecek** [comment]
I know this card is already refined. For the person who will spend time in that codebase, I'd appreciate if you could also look at this while at it https://github.com/packit/deployment/issues/345

**Comment by mfocko** [comment]
Update: created new repo to factor out the validation code to its own Python package: https://github.com/packit/validation

**Comment by mfocko** [comment]
I will create a follow-up issues in the said repo
