### ISSUE TITLE
Validation cron-job(s) for source-git bot(s)

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#435]
Start with [stream-prod](https://console-openshift-console.apps.auto-prod.gi0n.p1.openshiftapps.com/k8s/cluster/projects/stream-prod) validation by using the [redhat-internal-test-package](https://github.com/packit/deployment/blob/main/docs/centos-stream-source-git.md#redhat-internal-test-package).

See also #401

EDIT [Mar 1st]: Actually, I think we should start with [stream-stg](https://console-openshift-console.apps.auto-prod.gi0n.p1.openshiftapps.com/k8s/ns/stream-stg) first, to catch problems before they're propagated to prod

**Comment by lbarcziova** [comment]
The service [was shut down](https://packit.dev/source-git/shutdown), which means this is no longer relevant.
