### ISSUE TITLE
Move validation cron-job(s) from PSI to MP+

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#437]
In order to know how to proceed with the packit/private#13 (MP+) it'd be nice to have an overview of how demanding each subtask is, where we could potentially get stuck, what is a must and what's not so crucial, what we need to do first and what can actually wait. The easiest is to go through the process with something small and easy - the validation cron job(s).

Tasks will be added step by step.
Let's start with:

- [x] #438 
- [x] #453

**Comment by jpopelka** [comment]
Closing, we'll continue in packit/private#13

**Comment by mfocko** [comment]
Reopening with regards to decommissioning of the PSI instance where we run validation.

Though it might make sense to consider moving to one of the instances that will be proposed to the affected projects. (Running validation from the same instance where the service resides doesn't help in case of an outage of the service itself.)

cc @lbarcziova from the Slack discussion

**Comment by lbarcziova** [comment]
> Running validation from the same instance where the service resides doesn't help in case of an outage of the service itself.

+1, it would be the best to have it somewhere separate, let's wait for the proposed instances in the mail thread and discuss then.
