### ISSUE TITLE
MP+ firewall rules

### ISSUE THREAD

**Issue by mfocko** [packit/deployment#490]
When deploying to the MP+, based on the ESS requirement for monitoring the network traffic, **all** of the egress (outgoing network connections) are implicitly **denied** and must be requested to be allowed.

Links to relevant parts of the “documentation”:
* https://source.redhat.com/departments/it/devit/it-infrastructure/itcloudservices/itocp/managedplatformplushub/mppluswiki/user_tenant_onboarding_and_administration#application-external-egress
* https://source.redhat.com/departments/it/devit/it-infrastructure/itcloudservices/itocp/managedplatformplushub/mppluswiki/application_external_egress_osd_clusters

TODO:
- [x] Based on the documentation above, (presumably) create a ticket to sort out the firewall rules
   Preliminary list of the required domains (it may be required to translate to IP subnets :/):
   * pkgs.fedoraproject.org / src.fedoraproject.org
   * github.com
   * gitlab.com
   * gitlab.freedesktop.org
   * gitlab.gnome.org
   * salsa.debian.org
   * Copr
   * Image Builder
   * Koji
- [x] Investigate if there are any further actions to be taken, e.g. `src.fedoraproject.org` is reachable via `curl`, but not via `ssh` (similarly for `github.com`) (could've been a user error on my end though)

**Comment by mfocko** [comment]
Seems to be OK, GitHub and GitLab appears to be working, also reporting back is fine.

Unless there is an issue with some of the self-hosted GitLab instances or dist-git, I'd expect issues to appear during the sync-release jobs.

**Comment by mfocko** [comment]
Missed:
* Testing Farm (`api.dev.testing-farm.io`)

**Comment by mfocko** [comment]
Latest update:

- blocked on the ticket with regards to the 22 (SSH) port for `gitlab.com`; this could be also adjusted on our end to use HTTPS with PAT (token)
- also depends on packit/packit-service#2130

**Comment by mfocko** [comment]
Pinged on the ticket, moving to blocked till we get a response

**Comment by mfocko** [comment]
Scraped from the specfiles:
* go.dev
* pigeonhole.dovecot.org
* dovecot.org

@mfocko to create a ticket

**Comment by lachmanfrantisek** [comment]
:tada:
