### ISSUE TITLE
MP+ logging to Splunk

### ISSUE THREAD

**Issue by jpopelka** [packit/deployment#519]
[Our image](https://github.com/packit/fluent-plugin-splunk-hec) for sending logs to Splunk
  - [will reach End of Support on January 1, 2024](https://github.com/packit/fluent-plugin-splunk-hec#end-of-support)
  - tries to send the logs to [http-inputs-rhcorporate.splunkcloud.com](https://source.redhat.com/departments/it/splunk/splunk_wiki/splunk_fy20_architecture_blueprint#splunk-http-event-collectors-hec-) which is blocked by the firewall. The firewall allows `http-inputs-osdsecuritylogs.splunkcloud.com` which I tried, but our token doesn't work with it.

Per [internal docs](https://source.redhat.com/departments/it/devit/it-infrastructure/itcloudservices/itocp/it_paas_kb/logging_to_splunk_on_managed_platform) the logs from MP+ nodes should automatically go to Splunk if we log to `stdout` so we probably don't need to do the log-forwarding ourselves anymore.

For example [this search query](https://rhcorporate.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22rh_paas%22%20source%3D%22%2Fvar%2Flog%2Fcontainers%2Fpackit-worker-short-running-0_packit--stg_packit-worker-*.log%22) seems to work OK.

The task here is to:

- [ ] If the above query doesn't return any results, [request access](https://source.redhat.com/departments/it/splunk/splunk_wiki/faq#jive_content_id_How_do_I_request_access_to_additional_data_sets_in_Splunk) to `rh_paas` index for yourself and tell the other team members to do so as well
- [ ] Make sure our logs are there
- [ ] Update the [docs](https://github.com/packit/deployment/blob/main/docs/deployment/logs.md)
- [ ] Stop using the [fluentd sidecar](https://github.com/packit/deployment/blob/main/openshift/packit-worker.yml.j2#L154) (just set the `with_fluentd_sidecar: false` as a start)

**Comment by mfocko** [comment]
IIRC the ESS requires logging, am I to naïve, if I expect them to have some logging in-place within the cluster?

**Comment by jpopelka** [comment]
The `SEC-MON-REQ-1 (Logging & Monitoring)` is only for RH Internal/Restricted classified data (not our case) and the `SEC-NET-REQ-5 (Monitor Egress - outgoing internet traffic)` is about logging outgoing network connections (i.e. logging on the infra/networking level, not application level, AFAIK).

Yes, I was also expecting something more streamlined than "build your own splunk forwarder image from our Dockerfile and run it as a sidecar container in each pod".

**Comment by jpopelka** [comment]
The `SEC-MON-REQ-1 (Logging & Monitoring)` is only for RH Internal/Restricted classified data (not our case) and the `SEC-NET-REQ-5 (Monitor Egress - outgoing internet traffic)` is about logging outgoing network connections (i.e. logging on the infra/networking level, not application level, AFAIK), so we're not required to do that.

Yes, I was also expecting something more streamlined than "build your own splunk forwarder image from our Dockerfile and run it as a sidecar container in each pod".

**Comment by lachmanfrantisek** [comment]
Please, ask if you need any help when working on that.

**Comment by jpopelka** [comment]
I was either blind or reading too hastily because the [docs](https://source.redhat.com/departments/it/devit/it-infrastructure/itcloudservices/itocp/it_paas_kb/logging_to_splunk_on_managed_platform#jive_content_id_Logging_to_stdout) is quite clear that we just need to log to `stdout` to see the logs in Splunk. I updated the description above.

**Comment by majamassarini** [comment]
Wait for both stg and prod instances be in MP+ before merging PR.

**Comment by mfocko** [comment]
We're actually using it for some time already, I just need to clean up my branch and merge it, so I think that we can close this as done. :)
