### ISSUE TITLE
Migrate 'packit/deployment' to 'Webhook To Fedora Messaging'

### ISSUE THREAD

**Issue by gridhead** [packit/deployment#611]
This project was listed in the [**GitHub2FedMsg**](https://github.com/fedora-infra/github2fedmsg) database and we want to you to inform you about the upcoming deprecation of the service. As the [**Fedora Infrastructure**](https://docs.fedoraproject.org/en-US/infra/) is finishing up with migrating its applications away from [**FedMsg**](https://github.com/fedora-infra/fedmsg) to [**Fedora Messaging**](https://github.com/fedora-infra/fedora-messaging), we encourage you to migrate your repository to the successor of the [**GitHub2FedMsg**](https://fedora-arc.readthedocs.io/en/latest/github2fedmsg/index.html) project, [**Webhook To Fedora Messaging**](https://webhook2fedmsg.apps.ocp.fedoraproject.org/docs).

Please follow [this link](https://communityblog.fedoraproject.org/announcing-webhook-to-fedora-messaging/) to the official announcement of the project’s release and use the instructions there to [migrate](https://pagure.io/fedora-infra/w2fm-migration/issues) to the new service. If this notification was a mistake, please close this notification ticket. We will not act on the repositories whose migrations have not been requested and any related GitHub2FedMsg operations will stop working once the service is decommissioned.

**Comment by abompard** [comment]
Yes, you got that right. We've opened a tracker because the login process via Swagger UI isn't very well streamlined, but if you prefer doing it directly then yeah please do! :-)

**Comment by mfocko** [comment]
> Yes, you got that right. We've opened a tracker because the login process via Swagger UI isn't very well streamlined, but if you prefer doing it directly then yeah please do! :-)

Thanks a lot, appears to be done, got 202 back from the initial ping :tada:

Closes packit/rpm-shim#19
Closes packit/helm#31
Closes packit/configuration-migrations#2
Closes packit/contributing#40
Closes packit/status#168
Closes packit/prepare-release#32
Closes packit/agile#673
Closes packit/research#218
Closes packit/actions#20
Closes packit/specfile#422
Closes packit/dist-git-to-source-git#248
Closes packit/upsint#66
Closes packit/sandcastle#211
Closes packit/requre#289
Closes packit/pre-commit-hooks#46
Closes packit/packit-service-fedmsg#116
Closes packit/packit-service#2618
Closes packit/packit.dev#965
Closes packit/packit#2459
Closes packit/ogr#870
Closes packit/dashboard#479
