### ISSUE TITLE
Switch workers to Fedora to support newer macros

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/deployment#613]
Since people started using new ~~macros~~ RPM functionalities that are not available (and probably won't be) on CentOS Stream 9, let's switch our workers to Fedora to help in this situation.

Long-term, we need to research how to provide matching environment: https://github.com/packit/research/issues/219

**Comment by nforro** [comment]
> Since people started using new macros that are not available (and probably won't be) on CentOS Stream 9, let's switch our workers to Fedora to help in this situation.

It's not about macros (that can be [handled](https://github.com/packit/packit/issues/2404) e.g. with mock or just by preparing a suitable environment for rpm), it's about new rpm features that won't be available in older/more stable distributions.

When we switch to rpm 4.20, spec files using `%patchN` syntax will become unparseable, however that shouldn't be a problem on Fedora where all packages have been mass-converted, though it could be an issue on CentOS Stream.

**Comment by lachmanfrantisek** [comment]
Please, try running tests before deployment.
