### ISSUE TITLE
Configuring Secrets while deploying packit service for development

### ISSUE THREAD

**Issue by anirudhnarayanan** [packit/deployment#73]
I see there is a requirement of the following files:

private-key.pem - mentioned in the secrets list in

https://github.com/packit-service/deployment/blob/master/secrets/README.md

This might be a mundane question, but the documentation asks me to generate a private key using a github app. 
https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app
Do I need to create a new Github app for the same?  How exactly am I to proceed regarding creating the private key pem

**Comment by TomasTomecek** [comment]
It depends what you want to achieve: if you want to run packit-service locally and let it do things, you indeed need to create the github app. If you intend to work on a piece of code without the running the full deployment, you can mock some of the secrets. We do such a thing in CI, you can get inspired: https://github.com/packit-service/packit-service/blob/master/files/deployment.yaml#L40

**Comment by anirudhnarayanan** [comment]
In my case, I am working with some code , but I am working with an issue with the git refs, and believe I would benefit from creating a github app, and running it locally, however I am having an issue with the secrets. I may be wrong with my approach here, but I plan on doing so using ngrok (as mentioned), and generating the certificate (let's encrypt). Is that an approach that I might benefit in taking?

**Comment by TomasTomecek** [comment]
> In my case, I am working with some code , but I am working with an issue with the git refs, and believe I would benefit from creating a github app, and running it locally, however I am having an issue with the secrets. I may be wrong with my approach here, but I plan on doing so using ngrok (as mentioned), and generating the certificate (let's encrypt). Is that an approach that I might benefit in taking?

Yup, that should work, that's best way of doing it. Please let us know if we can help you out in any way.
